from __future__ import annotations

import inspect

from .. import trace_cpy
from ..inspector import extract_variables
from ..syntaxerror import extract_enhanced_positions
from .constants import (
    Range,
    _chain_reason,
    _create_summary,
    chainmsg,
    compute_cursor_position,
    ipython,
    libdir,
    symbols,
    symdesc,
)
from .digest import (
    _build_frame_ranges,
    _build_position_map,
    _digest_exception,
    _digest_exception_chain,
    _digest_frames,
    _extract_emphasis_columns,
    _extract_single_frame,
    _extract_subexception_chain,
    _extract_subexceptions,
    _extract_syntax_error_frame,
    _extract_text_from_range,
    _fallback_source_lines,
    _find_comprehension_range,
    _find_except_start_for_line,
    _get_full_source,
    _get_qualified_function_name,
    _get_source_from_frame,
    _get_source_lines_from_code,
    _get_variable_source_for_comprehension,
    _is_exception_group,
    _is_notebook_cell,
    _resolve_syntax_error_source,
    _slice_source_context,
    _slice_syntax_error_window,
    _syntax_error_positions,
    _trim_source_to_comprehension,
    _trim_to_except_line,
    _valid_error_position,
    extract_frames,
    extract_source_lines,
    format_location,
)
from .finalize import (
    _attach_leaf_types,
    _collect_leaf_exception_types,
    _fill_chronological_variables,
    _fill_frame_variables,
    _fill_variables,
    _finalize_chronological,
    _finalize_python_order_exception,
    _finalize_python_order_frames,
    _finalize_python_order_subexceptions,
    _set_chain_relevances,
    _set_relevances,
    build_chain_header,
    call_run_ranges,
    exception_info,
    extract_chain,
    extract_chain_exceptions,
    extract_exception,
    function_display,
    normalize_variable,
)
from .fragments import (
    _calculate_common_indent,
    _CodeScanner,
    _collect_positions_from_ranges,
    _convert_range_to_positions,
    _count_bracket_depth,
    _create_fragments_with_highlighting,
    _create_highlighted_fragments_unified,
    _create_unified_fragments,
    _dedent_lines,
    _fallback_mark_range_for_line,
    _find_clean_start_line,
    _find_comment_start,
    _get_highlight_boundaries,
    _get_highlight_status,
    _make_trace_id,
    _parse_line_to_fragments_unified,
    _parse_lines_to_fragments,
    _positions_to_consecutive_ranges,
    _process_indentation,
    _split_line_content,
)
from .order import (
    _add_subexceptions_to_frame,
    _analyze_exception_chain_links,
    _append_copied_frame,
    _apply_base_exception_suppression,
    _build_backbone_frames,
    _build_chronological_frames,
    _build_linked_backbone,
    _build_unlinked_backbone,
    _enrich_chain_with_links,
    _filter_hidden_frames,
    _find_chain_link,
    _find_last_bug_frame,
    _find_re_raise_frames,
    _frame_in_except_handler,
    _get_frame_lineno,
    _get_try_except_blocks,
    _make_exception_banner,
    _merge_suppressed_data,
    _promote_to_except,
    _split_suppressed_frames,
)

__all__ = [
    "Range",
    "build_chain_header",
    "call_run_ranges",
    "chainmsg",
    "compute_cursor_position",
    "exception_info",
    "extract_chain",
    "extract_chain_exceptions",
    "extract_exception",
    "extract_frames",
    "extract_source_lines",
    "format_location",
    "function_display",
    "ipython",
    "libdir",
    "normalize_variable",
    "symdesc",
    "symbols",
]
